GRAPEFRUIT_VERSION_MAJOR = 0
GRAPEFRUIT_VERSION_MINOR = 5
GRAPEFRUIT_VERSION_PATCH = 4
GRAPEFRUIT_BUILD = `git rev-parse --short HEAD`
GITHUB_URL  =   'https://github.com/grapefruitdotlink/grapefruit'
CHANGELOG_URL = 'http://grapefruit.link/tagged/changelog'
ORG_URL  =   'http://rpi.edu'
ORG_NAME =   'Rensselaer Polytechnic Institute'
ORG_NAME_SHORT = 'RPI'
DATE_FORMAT_DAY = '%B %-d, %Y'
